config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
  end
  root 'posts#index'
  get 'index' ,to: 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :body ,presence: true
    validates_length_of :body, minimum: 3, maximum: 100
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title ,presence: true
    validates :description ,presence: true 
    validates_length_of :title, minimum: 3, maximum: 20
    validates_length_of :description, minimum: 10, maximum: 100
    has_many :comments,dependent: :destroy
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,:confirmable,
         :recoverable, :rememberable, :validatable
  def is_admin?
    is_admin
  end
  validates :name ,presence: true
  validates :lastname ,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :lastname])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :lastname])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(params[:comment].permit( :body))
        redirect_to post_path(@post)
      end

      def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post) 
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: %i[ update destroy show edit]
    def index
        @posts = Post.all
    end
    def new
        @post = Post.new
    end

    def show
    
    end

    def edit
    end
    def create
        @post = Post.new(post_params)
        respond_to do |format|
            if @post.save
              format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
              format.json { render :show, status: :created, location: @post }
            else
              format.html { render :new, status: :unprocessable_entity }
              format.json { render json: @post.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
          if @post.update(post_params)
            format.html { redirect_to post_url(@post), notice: "post was successfully updated." }
            format.json { render :show, status: :ok, location: @post }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @post.errors, status: :unprocessable_entity }
          end
        end
    end

    def destroy
        @post.destroy
    
        respond_to do |format|
          format.html { redirect_to posts_url, notice: "post was successfully destroyed." }
          format.json { head :no_content }
        end
    end
    def set_post
        @post = Post.find(params[:id])
    end
  
    def post_params
         params.require(:post).permit(:title, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def show
      @user = User.find(params[:id])
    end

    def index 
    	@users = User.all 
    end

    def destroy
      @user.destroy
     redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div class="cmnts">
  <strong><%= comment.body.html_safe %></strong>
  <p class="text-muted">posted <%= time_ago_in_words(comment.created_at) %> ago</p>
 <% if current_user && current_user.is_admin?%>
    <p><%= button_to 'Delete comment',[comment.post, comment],class: 'btn btn-xs btn-danger', method: :delete, data: {confirm: "Are you sure?"} %></p>
 <%end%>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %> 
  
  <div class="form-group">
    
    <%= f.label :comment, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">    
      <%= f.text_area :body, :class => 'form-control', required: true  %>
    </div>
    </div>
    
  <p>
    <%= f.submit 'submit' %>
  </p>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">BLOG APP</a>
    </div>
    <ul class="nav navbar-nav">
     <li>
          <%= link_to('HOME', root_path, title: 'home page') %>
        </li>
    <% if current_user && current_user.is_admin? %>
      <li><%= link_to "<i class='fa fa-users'></i> Add Posts".html_safe,
                      new_post_path,
                      class: 'navbar-link btn btn' %></li>
      
      <li><%= link_to "View User" ,users_path, class: 'navbar-link btn btn' %></li>
    </ul>
    <%end%>
    
    <ul class="nav navbar-nav navbar-right">
    
     
      <% if current_user %>
      <li >
          <%= link_to('EDIT PROFILE', edit_user_registration_path, title: 'edit profile') %>
        </li>
      <li> <%= link_to "SIGN OUT" ,destroy_user_session_path, :method => :delete ,class: "btn btn-xs btn-danger" %> </li> 
      <%else%>
       
       <li >
          <%= link_to('Sign In', new_user_session_path, title: 'Sign In') %>
        </li>
         <li >
          <%= link_to('Sign up', new_user_registration_path, title: 'Sign up') %>
        </li>
      
    </ul>
  </div>
  <% end%>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MyApp" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %> 
    <%= javascript_include_tag "application" %>

  </head>
  <body>
  <%=render "layouts/navigation" %>
  

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        
      </div><!--/row-->

      

    </div> <!-- /container -->

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :class => "form-horizontal post" } do |f| %>

  <% if @post.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">    
      <%= f.text_area :description, :class => 'form-control'  %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                posts_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.id, post_path(post) %></td>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      post_path(post), :class => 'btn btn-default btn-success' %>
      <%if current_user&&current_user.is_admin?%>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_post_path(post), :class => 'btn btn-default btn-xs' %>
                      <%end%>
          
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<%- model_class = Post -%>
    <div class="page-header">
       <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
    </div>
   
    <div class="row">
    <div class="card text-black bg-info mb-3 shw"  >
     <div class="container">
     
    <p style="font-size:160%;"><strong><u><%= @post.title %></u></strong></p>
    <div class="card-body">
      <p style="font-size:160%;"><%= @post.description %></p>
    </div>
    </div>
    <div class="comment">
  <%= render @post.comments %>
  <% if current_user%>
  <%= render "comments/form" %>
</div>
<% if current_user && current_user.is_admin?%>
    <%= link_to t('.back', :default => t("helpers.links.back")),
                posts_path, :class => 'btn btn-default'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_post_path(@post), :class => 'btn btn-default' %>          
    <%= button_to t('.destroy', :default => t("helpers.links.destroy")),
                post_path(@post),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
    </div>
    <%end%>
    <%end%>
    
    </div>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table class="table table-striped">
  <thead>
    <tr>
      
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        
        <td><%= user.name %></td>
        <td><%= user.lastname %></td>
        <td><%= user.email %></td>
       
       <td>
        <%= link_to 'show',
                      user_path(user), :class => 'btn btn-default btn-success' %>
       </td>
       
      </tr>
    <% end %>
  </tbody>
</table>

<br>


app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="row" id="c">
<div class="card text-white bg-info mb-3 shw"  >
  <div class="card-header"><strong>PROFILE OF   <%= @user.name %></strong></div>
  <div class="card-body">
    <h5 class="card-title">USER EMAIL ID:<%= @user.email %></h5>
    <p class="card-text">
                         FIRST NAME: <%= @user.name %><br>
                         LAST  NAME: <%= @user.lastname %><br>
                       

    </p>
  </div>
  <%= link_to  'Back to users',
              users_path, :class => 'btn btn-info'  %>
 
</div>

</div>